
-- Create table TBL_ITEM
CREATE TABLE TBL_ITEM (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(19,2) NOT NULL,
    IS_ACTIVE BOOLEAN NULL,
    CREATED_BY BIGINT NULL,
    CREATED_DATE TIMESTAMP NULL,
    MODIFIED_BY BIGINT NULL,
    MODIFIED_DATE TIMESTAMP NULL
);