
-- Create table TBL_ITEM
CREATE TABLE TBL_ITEM (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(19,2) NOT NULL,
    IS_ACTIVE BOOLEAN NULL,
    CREATED_BY BIGINT NULL,
    CREATED_DATE TIMESTAMP NULL,
    MODIFIED_BY BIGINT NULL,
    MODIFIED_DATE TIMESTAMP NULL
);

-- create table TBL_OFFER
CREATE TABLE TBL_OFFER (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITEM_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    OFFER_PRICE DECIMAL(19,2) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    IS_ACTIVE BOOLEAN NULL,
    CREATED_BY BIGINT NULL,
    CREATED_DATE TIMESTAMP NULL,
    MODIFIED_BY BIGINT NULL,
    MODIFIED_DATE TIMESTAMP NULL,

    CONSTRAINT FK_OFFER_ITEM FOREIGN KEY (ITEM_ID)
        REFERENCES TBL_ITEM  (ID)
);