CREATE TABLE TBL_CHECKOUT (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TOTAL_PRICE DECIMAL(19,2) NOT NULL DEFAULT 0,
    TOTAL_DISCOUNT DECIMAL(19,2) NOT NULL DEFAULT 0,

    IS_ACTIVE BOOLEAN NULL,
    CREATED_BY BIGINT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY BIGINT NULL,
    MODIFIED_DATE TIMESTAMP NULL
);