CREATE TABLE TBL_CHECKOUT_ITEM (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITEM_ID BIGINT NOT NULL,
    ITEM_NAME VARCHAR(255) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    UNIT_PRICE DECIMAL(19,2) NOT NULL,
    TOTAL_PRICE DECIMAL(19,2)NOT NULL,
    ORIGINAL_TOTAL_PRICE DECIMAL(19,2) NOT NULL,
    DISCOUNT_APPLIED DECIMAL(19,2) NOT NULL DEFAULT 0,
    TIMES_OFFER_APPLIED BIGINT NOT NULL DEFAULT 0,

    CHECKOUT_ID BIGINT NOT NULL,

    IS_ACTIVE BOOLEAN NULL,
    CREATED_BY BIGINT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY BIGINT NULL,
    MODIFIED_DATE TIMESTAMP NULL,

    CONSTRAINT fk_checkout
        FOREIGN KEY (CHECKOUT_ID)
        REFERENCES TBL_CHECKOUT(ID)
        ON DELETE CASCADE
);